### ISSUE TITLE
Want to clear some fundamental concepts !!

### ISSUE THREAD

**Issue by utkarsh181** [jarun/binprint#1]
```
	if (val < 0) {
		val = ~val + 1;
		if (val > 0)
			printf("-0b");
```
Is there any case where value will not be greater than 0. ??

```
	count++;

	printf("%s", binstr + count);
```
I know this has to do something with trailing zero but I don't know how is this working and I can't find any reference to understand it.

And btw, thanks for nnn and this program was really helpful in understanding how bitwise operators work because before this I was not able to find a practical example for bitwise operators.

**Comment by jarun** [comment]
```
if (val < 0) {
		val = ~val + 1;
		if (val > 0)
			printf("-0b");
```

Where do you see this?

For the second question, `binstr + count` will always be a string ending in `NUL`.

**Comment by jarun** [comment]
Closing as it's not an issue.
